/**
 * Example: Pinia store for client-only auth state
 * Generated by /component-gen vue useAuthStore
 *
 * Demonstrates:
 * - Pinia setup store syntax (Composition API style)
 * - Typed state with explicit interfaces (no `any`)
 * - Getters for derived state
 * - Actions that mutate state via store methods (not direct mutation)
 * - pinia-plugin-persistedstate for session survival
 * - Clear separation: auth tokens/session = Pinia, user profile = TanStack Query
 */

import { ref, computed } from 'vue';
import { defineStore } from 'pinia';

interface AuthUser {
  id: string;
  email: string;
  name: string;
}

export const useAuthStore = defineStore(
  'auth',
  () => {
    // ── State ──────────────────────────────────────────────────────

    const user = ref<AuthUser | null>(null);
    const accessToken = ref<string | null>(null);

    // ── Getters ────────────────────────────────────────────────────

    const isAuthenticated = computed(() => user.value !== null);

    const userInitial = computed(() =>
      user.value?.name ? user.value.name.charAt(0).toUpperCase() : ''
    );

    // ── Actions ────────────────────────────────────────────────────

    function setAuth(authUser: AuthUser, token: string): void {
      user.value = authUser;
      accessToken.value = token;
    }

    function clearAuth(): void {
      user.value = null;
      accessToken.value = null;
    }

    return {
      // state
      user,
      accessToken,
      // getters
      isAuthenticated,
      userInitial,
      // actions
      setAuth,
      clearAuth,
    };
  },
  {
    persist: {
      pick: ['user'],
      // accessToken intentionally excluded from persistence
      // Use refresh token flow via /auth/refresh endpoint instead
    },
  }
);
