<!--
  Example: Vue component with all 4 states
  Generated by /component-gen vue UserCard

  Demonstrates:
  - TanStack Vue Query
  - <script setup lang="ts"> (Composition API)
  - defineProps with TypeScript generic
  - All 4 states: loading / error / empty / success
  - Accessible loading and error states
-->
<script setup lang="ts">
import { computed } from 'vue';
import { useQuery } from '@tanstack/vue-query';

interface UserCardProps {
  userId: string;
}

interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

const props = defineProps<UserCardProps>();

async function fetchUser(userId: string): Promise<User> {
  const response = await fetch(
    `${import.meta.env.VITE_API_BASE_URL}/users/${userId}`
  );
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: Failed to fetch user`);
  }
  return response.json() as Promise<User>;
}

const { data: user, isLoading, isError, refetch } = useQuery<User>({
  queryKey: computed(() => ['user', props.userId]),
  queryFn: () => fetchUser(props.userId),
  staleTime: 5 * 60 * 1000,
});

const initial = computed(() =>
  user.value?.name ? user.value.name.charAt(0).toUpperCase() : ''
);
</script>

<template>
  <!-- Loading state -->
  <div
    v-if="isLoading"
    role="status"
    aria-label="Loading user profile"
    class="space-y-3"
  >
    <div class="h-12 w-12 animate-pulse rounded-full bg-gray-200" />
    <div class="h-4 w-32 animate-pulse rounded bg-gray-200" />
    <div class="h-3 w-48 animate-pulse rounded bg-gray-200" />
    <span class="sr-only">Loading user profile...</span>
  </div>

  <!-- Error state -->
  <div
    v-else-if="isError"
    role="alert"
    class="rounded-lg border border-red-200 bg-red-50 p-4"
  >
    <p class="text-sm font-medium text-red-800">Failed to load user profile.</p>
    <button
      type="button"
      class="mt-2 text-sm text-red-600 underline hover:text-red-800"
      @click="refetch()"
    >
      Try again
    </button>
  </div>

  <!-- Empty state -->
  <div
    v-else-if="!user"
    class="rounded-lg border border-gray-200 p-6 text-center"
  >
    <p class="text-sm text-gray-500">User not found.</p>
  </div>

  <!-- Success state -->
  <article
    v-else
    :aria-label="`Profile of ${user.name}`"
    class="rounded-lg border border-gray-200 p-4"
  >
    <div class="flex items-center gap-3">
      <div class="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
        <span class="text-lg font-semibold text-blue-700" aria-hidden="true">
          {{ initial }}
        </span>
      </div>
      <div>
        <h2 class="font-semibold text-gray-900">{{ user.name }}</h2>
        <p class="text-sm text-gray-500">{{ user.email }}</p>
      </div>
    </div>
  </article>
</template>
