/**
 * Example: React streaming feature tests
 * Generated by /component-tests react StreamingFeature
 *
 * Demonstrates:
 * - Mock fetch with a controlled ReadableStream
 * - Testing idle, connecting, streaming (mid-stream entries), done, and error states
 * - AbortController called on unmount (memory-leak guard)
 * - role/label selectors only (no querySelector)
 * - userEvent for interactions
 */

import { render, screen, waitFor, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import StreamingFeature from "./StreamingFeature";

// ---------------------------------------------------------------------------
// Helpers — controllable ReadableStream factory
// ---------------------------------------------------------------------------

interface StreamController {
  push: (chunk: string) => void;
  close: () => void;
  error: (err: Error) => void;
}

function makeReadableStream(): { stream: ReadableStream<Uint8Array>; ctrl: StreamController } {
  let push: (chunk: string) => void;
  let close: () => void;
  let error: (err: Error) => void;

  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      const encoder = new TextEncoder();
      push = (chunk: string) => controller.enqueue(encoder.encode(chunk));
      close = () => controller.close();
      error = (err: Error) => controller.error(err);
    },
  });

  return {
    stream,
    ctrl: {
      push: push!,
      close: close!,
      error: error!,
    },
  };
}

function makeFetchResponse(stream: ReadableStream<Uint8Array>, ok = true, status = 200) {
  return Promise.resolve(
    new Response(stream, {
      status,
      headers: { "Content-Type": "application/x-ndjson" },
    })
  );
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const mockFetch = vi.fn<typeof fetch>();

beforeEach(() => {
  vi.stubGlobal("fetch", mockFetch);
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("StreamingFeature", () => {
  it("renders idle (empty) state with Start button on mount", () => {
    render(<StreamingFeature streamUrl="/api/stream" />);

    expect(screen.getByRole("region", { name: /stream monitor/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /start stream/i })).toBeEnabled();
    expect(screen.queryByRole("status")).not.toBeInTheDocument();
  });

  it("shows connecting skeleton after Start is clicked", async () => {
    const user = userEvent.setup();
    // Fetch never resolves during this test
    mockFetch.mockReturnValue(new Promise(() => {}));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    expect(await screen.findByRole("status", { name: /connecting to stream/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /cancel/i })).toBeEnabled();
  });

  it("renders streaming state with live entries as chunks arrive", async () => {
    const user = userEvent.setup();
    const { stream, ctrl } = makeReadableStream();
    mockFetch.mockReturnValue(makeFetchResponse(stream));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    // Wait for connecting state to resolve into streaming
    await waitFor(() => {
      expect(screen.queryByRole("status", { name: /connecting/i })).not.toBeInTheDocument();
    });

    // Push a line-delimited JSON entry
    act(() => {
      ctrl.push('{"message":"Processing item 1"}\n');
    });

    await waitFor(() => {
      expect(screen.getByText(/processing item 1/i)).toBeInTheDocument();
    });

    // The live badge is visible
    expect(screen.getByText(/live/i)).toBeInTheDocument();

    act(() => {
      ctrl.push('{"message":"Processing item 2"}\n');
    });

    await waitFor(() => {
      expect(screen.getByText(/processing item 2/i)).toBeInTheDocument();
    });

    // Close stream without completing assertions about done (that's the next test)
    act(() => {
      ctrl.close();
    });
  });

  it("transitions to done state when stream closes", async () => {
    const user = userEvent.setup();
    const { stream, ctrl } = makeReadableStream();
    mockFetch.mockReturnValue(makeFetchResponse(stream));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    await waitFor(() => {
      expect(screen.queryByRole("status", { name: /connecting/i })).not.toBeInTheDocument();
    });

    act(() => {
      ctrl.push('{"message":"Task finished"}\n');
      ctrl.close();
    });

    // Done badge + summary + reset button
    await waitFor(() => {
      expect(screen.getByText(/complete/i)).toBeInTheDocument();
    });
    expect(screen.getByText(/1 message received/i)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /start new stream/i })).toBeEnabled();
  });

  it("shows error state when fetch returns non-OK status", async () => {
    const user = userEvent.setup();
    mockFetch.mockResolvedValue(new Response(null, { status: 500 }));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    const alert = await screen.findByRole("alert");
    expect(alert).toBeInTheDocument();
    expect(screen.getByText(/stream failed/i)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /try again/i })).toBeInTheDocument();
  });

  it("shows error state when fetch rejects", async () => {
    const user = userEvent.setup();
    mockFetch.mockRejectedValue(new Error("Network error"));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    await waitFor(() => {
      expect(screen.getByRole("alert")).toBeInTheDocument();
    });
    expect(screen.getByText(/network error/i)).toBeInTheDocument();
  });

  it("calls AbortController.abort() on unmount (memory-leak guard)", async () => {
    const user = userEvent.setup();
    // Stream never completes
    const { stream } = makeReadableStream();
    mockFetch.mockReturnValue(makeFetchResponse(stream));

    const abortSpy = vi.spyOn(AbortController.prototype, "abort");

    const { unmount } = render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    // Wait for fetch to be called (connecting state entered)
    await waitFor(() => {
      expect(mockFetch).toHaveBeenCalledOnce();
    });

    unmount();

    expect(abortSpy).toHaveBeenCalled();
  });

  it("returns to idle state after Cancel is clicked during streaming", async () => {
    const user = userEvent.setup();
    mockFetch.mockReturnValue(new Promise(() => {})); // never resolves

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    await screen.findByRole("button", { name: /cancel/i });
    await user.click(screen.getByRole("button", { name: /cancel/i }));

    // After abort resolves the AbortError, component goes back to idle
    await waitFor(() => {
      expect(screen.getByRole("button", { name: /start stream/i })).toBeInTheDocument();
    });
  });

  it("allows restarting after done state", async () => {
    const user = userEvent.setup();
    const { stream, ctrl } = makeReadableStream();
    mockFetch.mockReturnValue(makeFetchResponse(stream));

    render(<StreamingFeature streamUrl="/api/stream" />);
    await user.click(screen.getByRole("button", { name: /start stream/i }));

    await waitFor(() => {
      expect(screen.queryByRole("status", { name: /connecting/i })).not.toBeInTheDocument();
    });

    act(() => {
      ctrl.close();
    });

    await waitFor(() => {
      expect(screen.getByRole("button", { name: /start new stream/i })).toBeInTheDocument();
    });

    // Second run
    const { stream: stream2, ctrl: ctrl2 } = makeReadableStream();
    mockFetch.mockReturnValue(makeFetchResponse(stream2));

    await user.click(screen.getByRole("button", { name: /start new stream/i }));
    expect(await screen.findByRole("status", { name: /connecting/i })).toBeInTheDocument();

    act(() => {
      ctrl2.close();
    });

    await waitFor(() => {
      expect(screen.getByText(/complete/i)).toBeInTheDocument();
    });
  });
});
