/**
 * Example: React streaming feature with phase state machine + SSE/ReadableStream
 * Generated by /component-gen react StreamingFeature
 *
 * Demonstrates:
 * - Phase-driven state machine (PHASE_ACTIONS map controls which buttons are enabled)
 * - SSE/ReadableStream consumption via fetch + TextDecoderStream
 * - AbortController stored in useRef (NOT useState) — safe to abort on unmount
 * - useEffect cleanup: abort on unmount to prevent memory leaks
 * - All 4 required states: loading (connecting), error (with retry), empty (idle), success (streaming/done)
 * - No `any`, no `console.log`, no inline styles, no direct DOM access
 */

import { useCallback, useEffect, useRef, useState } from "react";
import type { Phase, StreamEntry, StreamingFeatureState } from "./StreamingFeature.types";
import { PHASE_ACTIONS } from "./StreamingFeature.types";

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function ConnectingSkeleton() {
  return (
    <div role="status" aria-label="Connecting to stream" className="space-y-3">
      <div className="h-4 w-48 animate-pulse rounded bg-gray-200" />
      <div className="h-4 w-64 animate-pulse rounded bg-gray-200" />
      <div className="h-4 w-40 animate-pulse rounded bg-gray-200" />
      <span className="sr-only">Connecting to stream…</span>
    </div>
  );
}

interface EntryListProps {
  entries: StreamEntry[];
  live: boolean;
}

function EntryList({ entries, live }: EntryListProps) {
  return (
    <ul
      aria-label="Stream log"
      aria-live={live ? "polite" : "off"}
      className="max-h-64 space-y-1 overflow-y-auto rounded-lg border border-gray-200 bg-gray-50 p-3"
    >
      {entries.map((entry) => (
        <li key={entry.id} className="font-mono text-sm text-gray-800">
          <span className="mr-2 text-xs text-gray-400" aria-hidden="true">
            {new Date(entry.timestamp).toLocaleTimeString()}
          </span>
          {entry.message}
        </li>
      ))}
    </ul>
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseStreamLine(line: string): { message: string } | null {
  const trimmed = line.trim();
  if (!trimmed || trimmed === "[DONE]") return null;
  try {
    const parsed: unknown = JSON.parse(trimmed);
    if (
      typeof parsed === "object" &&
      parsed !== null &&
      "message" in parsed &&
      typeof (parsed as Record<string, unknown>).message === "string"
    ) {
      return { message: (parsed as { message: string }).message };
    }
    return null;
  } catch {
    // Non-JSON line: treat raw text as message
    return { message: trimmed };
  }
}

function makeId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

interface StreamingFeatureProps {
  /** Endpoint that returns a line-delimited JSON (NDJSON) or plain-text stream */
  streamUrl: string;
}

export default function StreamingFeature({ streamUrl }: StreamingFeatureProps) {
  const [state, setState] = useState<StreamingFeatureState>({ status: "idle" });
  const [phase, setPhase] = useState<Phase>("idle");

  // AbortController lives in a ref — never triggers re-renders, safe to call in cleanup
  const abortRef = useRef<AbortController | null>(null);

  // Abort any active stream on unmount (memory-leak guard)
  useEffect(() => {
    return () => {
      abortRef.current?.abort();
    };
  }, []);

  const startStream = useCallback(async () => {
    if (!PHASE_ACTIONS.idle.has("start")) return;

    abortRef.current = new AbortController();
    setPhase("running");
    setState({ status: "connecting" });

    const entries: StreamEntry[] = [];

    try {
      const res = await fetch(streamUrl, {
        signal: abortRef.current.signal,
      });

      if (!res.ok) {
        throw new Error(`Server responded with ${res.status}`);
      }
      if (!res.body) {
        throw new Error("Response body is empty — streaming not supported");
      }

      setState({ status: "streaming", entries: [], summary: "" });

      const reader = res.body.pipeThrough(new TextDecoderStream()).getReader();
      let buffer = "";

      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += value;
          const lines = buffer.split("\n");
          // Keep the last (potentially incomplete) line in buffer
          buffer = lines.pop() ?? "";

          for (const line of lines) {
            const parsed = parseStreamLine(line);
            if (parsed) {
              entries.push({ id: makeId(), message: parsed.message, timestamp: Date.now() });
              setState({ status: "streaming", entries: [...entries], summary: "" });
            }
          }
        }

        // Flush remaining buffer
        if (buffer.trim()) {
          const parsed = parseStreamLine(buffer);
          if (parsed) {
            entries.push({ id: makeId(), message: parsed.message, timestamp: Date.now() });
          }
        }
      } finally {
        reader.releaseLock();
      }

      const summary = `${entries.length} message${entries.length !== 1 ? "s" : ""} received`;
      setState({ status: "done", entries: [...entries], summary });
      setPhase("done");
    } catch (err) {
      // Abort is intentional — go back to idle silently
      if (err instanceof DOMException && err.name === "AbortError") {
        setState({ status: "idle" });
        setPhase("idle");
        return;
      }
      const message =
        err instanceof Error
          ? `Stream failed — ${err.message}`
          : "Stream failed — please try again.";
      setState({ status: "error", message });
      setPhase("idle");
    }
  }, [streamUrl]);

  const cancelStream = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  const reset = useCallback(() => {
    setState({ status: "idle" });
    setPhase("idle");
  }, []);

  // ---------------------------------------------------------------------------
  // Render: empty (idle) state
  // ---------------------------------------------------------------------------
  if (state.status === "idle") {
    return (
      <section aria-label="Stream feature" className="rounded-lg border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-gray-900">Stream Monitor</h2>
        <p className="mt-1 text-sm text-gray-500">
          Start the stream to receive live progress updates.
        </p>
        <button
          type="button"
          onClick={() => void startStream()}
          disabled={!PHASE_ACTIONS[phase].has("start")}
          className="mt-4 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Start Stream
        </button>
      </section>
    );
  }

  // ---------------------------------------------------------------------------
  // Render: loading (connecting) state
  // ---------------------------------------------------------------------------
  if (state.status === "connecting") {
    return (
      <section aria-label="Stream feature" className="rounded-lg border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-gray-900">Stream Monitor</h2>
        <div className="mt-4">
          <ConnectingSkeleton />
        </div>
        <button
          type="button"
          onClick={cancelStream}
          disabled={!PHASE_ACTIONS[phase].has("cancel")}
          className="mt-4 rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Cancel
        </button>
      </section>
    );
  }

  // ---------------------------------------------------------------------------
  // Render: error state
  // ---------------------------------------------------------------------------
  if (state.status === "error") {
    return (
      <section aria-label="Stream feature" className="rounded-lg border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-gray-900">Stream Monitor</h2>
        <div role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-4">
          <p className="text-sm font-medium text-red-800">{state.message}</p>
          <button
            type="button"
            onClick={() => void startStream()}
            className="mt-2 text-sm text-red-600 underline hover:text-red-800"
          >
            Try again
          </button>
        </div>
      </section>
    );
  }

  // ---------------------------------------------------------------------------
  // Render: success (streaming) state
  // ---------------------------------------------------------------------------
  if (state.status === "streaming") {
    return (
      <section aria-label="Stream feature" className="rounded-lg border border-gray-200 p-6">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Stream Monitor</h2>
          <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-blue-500" aria-hidden="true" />
            Live
          </span>
        </div>
        <div className="mt-4">
          {state.entries.length === 0 ? (
            <p className="text-sm text-gray-500" aria-live="polite">
              Waiting for data…
            </p>
          ) : (
            <EntryList entries={state.entries} live={true} />
          )}
        </div>
        <button
          type="button"
          onClick={cancelStream}
          disabled={!PHASE_ACTIONS[phase].has("cancel")}
          className="mt-4 rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Cancel
        </button>
      </section>
    );
  }

  // ---------------------------------------------------------------------------
  // Render: success (done) state
  // ---------------------------------------------------------------------------
  return (
    <section aria-label="Stream feature" className="rounded-lg border border-gray-200 p-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-900">Stream Monitor</h2>
        <span className="inline-flex items-center gap-1.5 rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800">
          Complete
        </span>
      </div>
      <p className="mt-1 text-sm text-gray-500">{state.summary}</p>
      <div className="mt-4">
        <EntryList entries={state.entries} live={false} />
      </div>
      <button
        type="button"
        onClick={reset}
        disabled={!PHASE_ACTIONS[phase].has("start")}
        className="mt-4 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
      >
        Start New Stream
      </button>
    </section>
  );
}
