/**
 * Example: Concurrent React features
 * Generated by /component-gen react DeferredSearch
 *
 * Demonstrates:
 * - useTransition for expensive list filtering (urgent input vs deferred render)
 * - useDeferredValue for derived expensive computation
 * - Stale indicator while deferred value catches up
 * - Accessible search input with live results count
 * - No `any` types
 */

import { useState, useDeferredValue, useMemo } from 'react';

interface SearchItem {
  id: string;
  name: string;
  category: string;
}

interface DeferredSearchProps {
  items: SearchItem[];
}

/**
 * Search with useDeferredValue — input stays responsive while
 * the expensive filtered list renders at lower priority.
 *
 * When to use: Large lists (1,000+ items) where filtering causes
 * noticeable jank (>16ms render). For small lists, skip this.
 */
export default function DeferredSearch({ items }: DeferredSearchProps) {
  const [query, setQuery] = useState('');
  const deferredQuery = useDeferredValue(query);
  const isStale = query !== deferredQuery;

  // Expensive filtering runs with deferred value — doesn't block input
  const filteredItems = useMemo(() => {
    if (!deferredQuery) return items;
    const lower = deferredQuery.toLowerCase();
    return items.filter(
      (item) =>
        item.name.toLowerCase().includes(lower) ||
        item.category.toLowerCase().includes(lower)
    );
  }, [items, deferredQuery]);

  return (
    <div className="space-y-4">
      <div className="space-y-1">
        <label htmlFor="deferred-search" className="block text-sm font-medium text-gray-700">
          Search items
        </label>
        <input
          id="deferred-search"
          type="search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Filter by name or category…"
          aria-describedby="search-results-count"
          className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
        />
        <p id="search-results-count" className="sr-only" aria-live="polite">
          {filteredItems.length} results found
        </p>
      </div>

      <ul
        role="list"
        className="divide-y divide-gray-100 transition-opacity duration-150"
        style={{ opacity: isStale ? 0.7 : 1 }}
        aria-busy={isStale}
      >
        {filteredItems.length === 0 ? (
          <li className="py-4 text-center text-sm text-gray-500">
            No items match your search.
          </li>
        ) : (
          filteredItems.map((item) => (
            <li key={item.id} className="flex items-center justify-between py-3">
              <span className="text-sm font-medium text-gray-900">{item.name}</span>
              <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                {item.category}
              </span>
            </li>
          ))
        )}
      </ul>
    </div>
  );
}
