/**
 * Example: Form component tests
 * Generated by /component-tests react LoginForm
 *
 * Demonstrates:
 * - Testing form validation (Zod + React Hook Form)
 * - Testing submission states (loading, error, success)
 * - Accessible selectors (getByRole, getByLabelText)
 * - userEvent for form interactions
 * - No querySelector or getByTestId
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import LoginForm from './LoginForm';

const mockFetch = vi.fn();
global.fetch = mockFetch;

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  return function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    );
  };
}

describe('LoginForm', () => {
  const mockOnSuccess = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders email and password fields with labels', () => {
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });
    expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/password/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /sign in/i })).toBeInTheDocument();
  });

  it('shows validation errors for empty fields', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByText(/email is required/i)).toBeInTheDocument();
    expect(screen.getByText(/password is required/i)).toBeInTheDocument();
    expect(mockFetch).not.toHaveBeenCalled();
  });

  it('shows validation error for invalid email', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'not-an-email');
    await user.type(screen.getByLabelText(/password/i), 'validpassword123');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByText(/enter a valid email/i)).toBeInTheDocument();
  });

  it('shows validation error for short password', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'user@example.com');
    await user.type(screen.getByLabelText(/password/i), 'short');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByText(/at least 8 characters/i)).toBeInTheDocument();
  });

  it('disables button and shows loading text during submission', async () => {
    const user = userEvent.setup();
    mockFetch.mockReturnValue(new Promise(() => {})); // never resolves

    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'user@example.com');
    await user.type(screen.getByLabelText(/password/i), 'validpassword123');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /signing in/i })).toBeDisabled();
    });
  });

  it('shows server error message on failed login', async () => {
    const user = userEvent.setup();
    mockFetch.mockResolvedValue({
      ok: false,
      json: async () => ({
        code: 'INVALID_CREDENTIALS',
        message: 'Invalid email or password',
      }),
    });

    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'user@example.com');
    await user.type(screen.getByLabelText(/password/i), 'wrongpassword1');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByRole('alert')).toHaveTextContent(/invalid email or password/i);
  });

  it('calls onSuccess with response data on successful login', async () => {
    const user = userEvent.setup();
    const mockResponse = {
      accessToken: 'token-abc',
      refreshToken: 'refresh-xyz',
      user: { id: '1', email: 'user@example.com', name: 'Alice' },
    };
    mockFetch.mockResolvedValue({
      ok: true,
      json: async () => mockResponse,
    });

    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'user@example.com');
    await user.type(screen.getByLabelText(/password/i), 'validpassword123');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    await waitFor(() => {
      expect(mockOnSuccess).toHaveBeenCalledWith(mockResponse);
    });
  });

  it('sets aria-invalid on fields with validation errors', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.click(screen.getByRole('button', { name: /sign in/i }));

    await waitFor(() => {
      expect(screen.getByLabelText(/email/i)).toHaveAttribute('aria-invalid', 'true');
      expect(screen.getByLabelText(/password/i)).toHaveAttribute('aria-invalid', 'true');
    });
  });
});
