/**
 * Example: MSW (Mock Service Worker) integration test
 * Generated by /component-tests react LoginForm
 *
 * Demonstrates:
 * - MSW handlers for API mocking (de-facto standard, replaces vi.mock(fetch))
 * - Server setup with beforeAll/afterAll lifecycle
 * - Testing success and error flows with realistic HTTP responses
 * - No direct fetch mocking — MSW intercepts at network level
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { describe, it, expect, vi, beforeAll, afterAll, afterEach } from 'vitest';
import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';
import LoginForm from './LoginForm';

// ── MSW Server Setup ────────────────────────────────────────────────

const API_URL = 'http://localhost:3000';

const handlers = [
  // Default: successful login
  http.post(`${API_URL}/auth/login`, async ({ request }) => {
    const body = (await request.json()) as { email: string; password: string };

    if (body.email === 'locked@example.com') {
      return HttpResponse.json(
        { code: 'ACCOUNT_LOCKED', message: 'Account is locked. Contact support.' },
        { status: 423 }
      );
    }

    if (body.password !== 'correctpassword') {
      return HttpResponse.json(
        { code: 'INVALID_CREDENTIALS', message: 'Invalid email or password' },
        { status: 401 }
      );
    }

    return HttpResponse.json({
      accessToken: 'token-abc-123',
      refreshToken: 'refresh-xyz-456',
      user: { id: '1', email: body.email, name: 'Alice Smith' },
    });
  }),
];

const server = setupServer(...handlers);

beforeAll(() => {
  // Set VITE env for the component's fetch URL
  import.meta.env.VITE_API_BASE_URL = API_URL;
  server.listen({ onUnhandledRequest: 'error' });
});
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

// ── Helpers ─────────────────────────────────────────────────────────

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: { mutations: { retry: false } },
  });
  return function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    );
  };
}

// ── Tests ───────────────────────────────────────────────────────────

describe('LoginForm (MSW)', () => {
  const mockOnSuccess = vi.fn();

  it('submits valid credentials and calls onSuccess', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'alice@example.com');
    await user.type(screen.getByLabelText(/password/i), 'correctpassword');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    await waitFor(() => {
      expect(mockOnSuccess).toHaveBeenCalledWith(
        expect.objectContaining({
          accessToken: 'token-abc-123',
          user: expect.objectContaining({ email: 'alice@example.com' }),
        })
      );
    });
  });

  it('shows error for invalid credentials', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'alice@example.com');
    await user.type(screen.getByLabelText(/password/i), 'wrongpassword');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByRole('alert')).toHaveTextContent(/invalid email or password/i);
  });

  it('shows account locked error', async () => {
    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'locked@example.com');
    await user.type(screen.getByLabelText(/password/i), 'correctpassword');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByRole('alert')).toHaveTextContent(/account is locked/i);
  });

  it('handles network errors gracefully', async () => {
    // Override handler to simulate network failure
    server.use(
      http.post(`${API_URL}/auth/login`, () => {
        return HttpResponse.error();
      })
    );

    const user = userEvent.setup();
    render(<LoginForm onSuccess={mockOnSuccess} />, { wrapper: createWrapper() });

    await user.type(screen.getByLabelText(/email/i), 'alice@example.com');
    await user.type(screen.getByLabelText(/password/i), 'correctpassword');
    await user.click(screen.getByRole('button', { name: /sign in/i }));

    expect(await screen.findByRole('alert')).toBeInTheDocument();
  });
});
