/**
 * Example: Zustand store for client-only auth state
 * Generated by /component-gen react useAuthStore
 *
 * Demonstrates:
 * - Zustand store for CLIENT-ONLY state (not server data)
 * - Typed state and actions (no `any`)
 * - Selectors for fine-grained subscriptions
 * - persist middleware for session survival
 * - Clear separation: auth tokens/session = Zustand, user profile = TanStack Query
 */

import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface AuthUser {
  id: string;
  email: string;
  name: string;
}

interface AuthState {
  /** Current authenticated user (set on login, cleared on logout) */
  user: AuthUser | null;
  /** JWT access token — never persisted to localStorage in production */
  accessToken: string | null;
  /** Whether auth state has been hydrated from storage */
  isHydrated: boolean;
}

interface AuthActions {
  setAuth: (user: AuthUser, accessToken: string) => void;
  clearAuth: () => void;
  setHydrated: () => void;
}

type AuthStore = AuthState & AuthActions;

export const useAuthStore = create<AuthStore>()(
  persist(
    (set) => ({
      user: null,
      accessToken: null,
      isHydrated: false,

      setAuth: (user, accessToken) => set({ user, accessToken }),

      clearAuth: () => set({ user: null, accessToken: null }),

      setHydrated: () => set({ isHydrated: true }),
    }),
    {
      name: 'auth-storage',
      partialize: (state) => ({
        user: state.user,
        // accessToken intentionally excluded from persistence
        // Use refresh token flow via /auth/refresh endpoint instead
      }),
      onRehydrateStorage: () => (state) => {
        state?.setHydrated();
      },
    }
  )
);

// ── Selectors (prevent unnecessary re-renders) ──────────────────────

/** Use when you only need to check if user is logged in */
export const useIsAuthenticated = (): boolean =>
  useAuthStore((state) => state.user !== null);

/** Use when you need the user object */
export const useCurrentUser = (): AuthUser | null =>
  useAuthStore((state) => state.user);

/** Use in API interceptors to attach Authorization header */
export const useAccessToken = (): string | null =>
  useAuthStore((state) => state.accessToken);
