/**
 * Example: React component with all 4 states
 * Generated by /component-gen react UserCard
 *
 * Demonstrates:
 * - TanStack Query for server state
 * - Loading skeleton (accessible)
 * - Error state with retry
 * - Empty state
 * - Success state
 * - No `any` types
 */

import { useQuery } from '@tanstack/react-query';
import type { User } from './UserCard.types';

interface UserCardProps {
  userId: string;
}

async function fetchUser(userId: string): Promise<User> {
  const response = await fetch(
    `${import.meta.env.VITE_API_BASE_URL}/users/${userId}`
  );
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: Failed to fetch user`);
  }
  return response.json() as Promise<User>;
}

function UserCardSkeleton() {
  return (
    <div role="status" aria-label="Loading user profile" className="space-y-3">
      <div className="h-12 w-12 animate-pulse rounded-full bg-gray-200" />
      <div className="h-4 w-32 animate-pulse rounded bg-gray-200" />
      <div className="h-3 w-48 animate-pulse rounded bg-gray-200" />
      <span className="sr-only">Loading user profile...</span>
    </div>
  );
}

export default function UserCard({ userId }: UserCardProps) {
  const {
    data: user,
    isLoading,
    isError,
    refetch,
  } = useQuery<User>({
    queryKey: ['user', userId],
    queryFn: () => fetchUser(userId),
    staleTime: 5 * 60 * 1000,
  });

  // Loading state
  if (isLoading) {
    return <UserCardSkeleton />;
  }

  // Error state
  if (isError) {
    return (
      <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4">
        <p className="text-sm font-medium text-red-800">
          Failed to load user profile.
        </p>
        <button
          type="button"
          onClick={() => refetch()}
          className="mt-2 text-sm text-red-600 underline hover:text-red-800"
        >
          Try again
        </button>
      </div>
    );
  }

  // Empty state (user not found)
  if (!user) {
    return (
      <div className="rounded-lg border border-gray-200 p-6 text-center">
        <p className="text-sm text-gray-500">User not found.</p>
      </div>
    );
  }

  // Success state
  return (
    <article aria-label={`Profile of ${user.name}`} className="rounded-lg border border-gray-200 p-4">
      <div className="flex items-center gap-3">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
          <span className="text-lg font-semibold text-blue-700" aria-hidden="true">
            {user.name.charAt(0).toUpperCase()}
          </span>
        </div>
        <div>
          <h2 className="font-semibold text-gray-900">{user.name}</h2>
          <p className="text-sm text-gray-500">{user.email}</p>
        </div>
      </div>
    </article>
  );
}
