/**
 * Example: React component tests
 * Generated by /component-tests react UserCard
 *
 * Demonstrates:
 * - TanStack Query wrapper setup
 * - Testing all 4 states via vi.mock
 * - role/label selectors (no querySelector)
 * - userEvent for interactions
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import UserCard from './UserCard';

vi.mock('./UserCard', async (importOriginal) => {
  // We test the actual component but mock the fetch
  const mod = await importOriginal<typeof import('./UserCard')>();
  return mod;
});

// Mock global fetch
const mockFetch = vi.fn();
global.fetch = mockFetch;

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    );
  };
}

describe('UserCard', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('shows loading skeleton while fetching', () => {
    mockFetch.mockReturnValue(new Promise(() => {})); // never resolves
    render(<UserCard userId="1" />, { wrapper: createWrapper() });
    expect(screen.getByRole('status', { name: /loading user profile/i })).toBeInTheDocument();
  });

  it('shows error message when fetch fails', async () => {
    mockFetch.mockResolvedValue({ ok: false, status: 500 });
    render(<UserCard userId="1" />, { wrapper: createWrapper() });
    expect(await screen.findByRole('alert')).toBeInTheDocument();
    expect(screen.getByText(/failed to load user profile/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /try again/i })).toBeInTheDocument();
  });

  it('shows empty state when user not found', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: async () => null,
    });
    render(<UserCard userId="999" />, { wrapper: createWrapper() });
    expect(await screen.findByText(/user not found/i)).toBeInTheDocument();
  });

  it('renders user profile when data is available', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: async () => ({ id: '1', name: 'Alice Smith', email: 'alice@example.com' }),
    });
    render(<UserCard userId="1" />, { wrapper: createWrapper() });
    expect(await screen.findByRole('article')).toBeInTheDocument();
    expect(screen.getByText('Alice Smith')).toBeInTheDocument();
    expect(screen.getByText('alice@example.com')).toBeInTheDocument();
  });

  it('retries fetch when "Try again" button clicked', async () => {
    const user = userEvent.setup();
    mockFetch.mockResolvedValueOnce({ ok: false, status: 500 });
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({ id: '1', name: 'Alice Smith', email: 'alice@example.com' }),
    });

    render(<UserCard userId="1" />, { wrapper: createWrapper() });
    await screen.findByRole('alert');
    await user.click(screen.getByRole('button', { name: /try again/i }));
    await waitFor(() => {
      expect(mockFetch).toHaveBeenCalledTimes(2);
    });
  });
});
